// App.js
(function(){
Type.registerNamespace('GLSharp.Data');GLSharp.Data.IResourceLoader=function(){};GLSharp.Data.IResourceLoader.registerInterface('GLSharp.Data.IResourceLoader');GLSharp.Data.ImageLoader=function(){}
GLSharp.Data.ImageLoader.prototype={get_extension:function(){var $0=[];$0.add('.jpg');$0.add('.png');$0.add('.jpeg');return $0;},load:function(url){var $0=new GLSharp.Data.Resource();$0.set_finished(false);var $1=new Image();$1.onload=function(){
$0.set_finished(true);$0.set_data($1);};$1.src=url;return $0;}}
GLSharp.Data.JsonLoader=function(){}
GLSharp.Data.JsonLoader.prototype={get_extension:function(){var $0=[];$0.add('.json');return $0;},load:function(url){var $0=new GLSharp.Data.Resource();$0.set_finished(false);var $1=new XMLHttpRequest();$1.open('GET',url,true);$1.onreadystatechange=function(){
if($1.readyState===4&&$1.status===200){$0.set_finished(true);$0.set_data(JSON.parse($1.responseText));}};$1.send();return $0;}}
GLSharp.Data.ResourceManager=function(){this.$0={};}
GLSharp.Data.ResourceManager.prototype={$1:'',get_rootUrl:function(){return this.$1;},set_rootUrl:function(value){this.$1=value;return value;},getResource:function(resource){var $0=resource.lastIndexOf('.');var $1='';if($0>-1){$1=resource.substring($0,resource.length).toLowerCase();}var $2=this.$0[$1];if($2==null){throw new Error('The specified resource is unsuppoted');}return $2.load(this.get_rootUrl()+resource);},freeResource:function(resource){return false;},addLoader:function(loader){var $enum1=ss.IEnumerator.getEnumerator(loader.get_extension());while($enum1.moveNext()){var $0=$enum1.current;this.$0[$0.toLowerCase()]=loader;}},removeLoader:function(loader){var $enum1=ss.IEnumerator.getEnumerator(loader.get_extension());while($enum1.moveNext()){var $0=$enum1.current;delete this.$0[$0.toLowerCase()];}}}
Type.registerNamespace('GLSharp.Graphics');GLSharp.Graphics.Buffer=function(){}
GLSharp.Graphics.FrameBuffer=function(){}
GLSharp.Graphics.RenderBuffer=function(){}
GLSharp.Graphics.Shader=function(){}
GLSharp.Graphics.ShaderProgram=function(){}
GLSharp.Graphics.Texture=function(){}
GLSharp.Graphics.UniformLocation=function(){}
GLSharp.Graphics.WebGLGraphics=function(canvas){this.$3=GLSharp.Graphics.ClearMode.color;this.$0=canvas;this.$1=canvas.getContext('experimental-webgl');this.set_clearColor(GLSharp.Graphics.Color.create(0.3,0.6,0.9,1));}
GLSharp.Graphics.WebGLGraphics.prototype={$0:null,$1:null,$2:null,$4:null,get_height:function(){if(this.$0!=null){return this.$0.height;}return -1;},get_width:function(){if(this.$0!=null){return this.$0.width;}return -1;},get_clearColor:function(){return this.$2;},set_clearColor:function(value){this.$2=value;if(this.$1!=null){this.$1.clearColor(this.$2.get_red(),this.$2.get_green(),this.$2.get_blue(),this.$2.get_alpha());}return value;},get_clearMode:function(){return this.$3;},set_clearMode:function(value){this.$3=value;return value;},clear:function(){this.$1.clear(this.$3);},$5:function($p0){$p0.add_nodeAdded(ss.Delegate.create(this,this.$7));$p0.add_nodeRemoved(ss.Delegate.create(this,this.$6));},$6:function($p0,$p1){var $0=Type.safeCast($p1,GLSharp.Universe.Node);$0.add_componentAdded(ss.Delegate.create(this,this.$9));$0.add_componentRemoved(ss.Delegate.create(this,this.$8));},$7:function($p0,$p1){},$8:function($p0,$p1){},$9:function($p0,$p1){}}
Type.registerNamespace('App');App.App=function(){}
App.App.prototype={$0:null,init:function(){this.$1();var $0=document.getElementById('mainCanvas');if($0==null){throw new Error('No canvas element found!');}this.$0=new GLSharp.Graphics.WebGLGraphics($0);this.$0.clear();GLSharp.Core.Core.get_resourceManager().getResource('/Data/JSON/test.json').add_resourceChanged(function($p1_0,$p1_1){
alert('aaa');});},$1:function(){GLSharp.Core.Core.set_environment(new Environment());var $0=new GLSharp.Data.ResourceManager();$0.addLoader(new GLSharp.Data.ImageLoader());$0.addLoader(new GLSharp.Data.JsonLoader());GLSharp.Core.Core.set_resourceManager($0);}}
GLSharp.Data.ImageLoader.registerClass('GLSharp.Data.ImageLoader',null,GLSharp.Data.IResourceLoader);GLSharp.Data.JsonLoader.registerClass('GLSharp.Data.JsonLoader',null,GLSharp.Data.IResourceLoader);GLSharp.Data.ResourceManager.registerClass('GLSharp.Data.ResourceManager',null,GLSharp.Data.IResourceManager);GLSharp.Graphics.Buffer.registerClass('GLSharp.Graphics.Buffer');GLSharp.Graphics.FrameBuffer.registerClass('GLSharp.Graphics.FrameBuffer');GLSharp.Graphics.RenderBuffer.registerClass('GLSharp.Graphics.RenderBuffer');GLSharp.Graphics.Shader.registerClass('GLSharp.Graphics.Shader');GLSharp.Graphics.ShaderProgram.registerClass('GLSharp.Graphics.ShaderProgram');GLSharp.Graphics.Texture.registerClass('GLSharp.Graphics.Texture');GLSharp.Graphics.UniformLocation.registerClass('GLSharp.Graphics.UniformLocation');GLSharp.Graphics.WebGLGraphics.registerClass('GLSharp.Graphics.WebGLGraphics',null,GLSharp.Graphics.IGraphics);App.App.registerClass('App.App');})();// This script was generated using Script# v0.7.4.0
