// Engine.js
(function(){
Type.registerNamespace('GLSharp.Graphics');GLSharp.Graphics.ICompiledShader=function(){};GLSharp.Graphics.ICompiledShader.registerInterface('GLSharp.Graphics.ICompiledShader');GLSharp.Graphics.IUniform=function(){};GLSharp.Graphics.IUniform.registerInterface('GLSharp.Graphics.IUniform');GLSharp.Graphics.ClearMode=function(){};GLSharp.Graphics.ClearMode.prototype = {depth:256,stencil:1024,color:16384}
GLSharp.Graphics.ClearMode.registerEnum('GLSharp.Graphics.ClearMode',false);GLSharp.Graphics.IGraphics=function(){};GLSharp.Graphics.IGraphics.registerInterface('GLSharp.Graphics.IGraphics');GLSharp.Graphics.IShader=function(){};GLSharp.Graphics.IShader.registerInterface('GLSharp.Graphics.IShader');GLSharp.Graphics.IShaderProgram=function(){};GLSharp.Graphics.IShaderProgram.registerInterface('GLSharp.Graphics.IShaderProgram');GLSharp.Graphics.IUniformLocation=function(){};GLSharp.Graphics.IUniformLocation.registerInterface('GLSharp.Graphics.IUniformLocation');GLSharp.Graphics.Color=function(){}
GLSharp.Graphics.Color.create=function(red,green,blue,alpha){var $0=new GLSharp.Graphics.Color();$0.set_red(red);$0.set_green(green);$0.set_blue(blue);$0.set_alpha(alpha);return $0;}
GLSharp.Graphics.Color.prototype={$0:0,$1:0,$2:0,$3:1,get_red:function(){return this.$0;},set_red:function(value){this.$0=value;return value;},get_green:function(){return this.$1;},set_green:function(value){this.$1=value;return value;},get_blue:function(){return this.$2;},set_blue:function(value){this.$2=value;return value;},get_alpha:function(){return this.$3;},set_alpha:function(value){this.$3=value;return value;}}
GLSharp.Graphics.Material=function(){}
GLSharp.Graphics.Material.prototype={$0:null,get_shader:function(){return this.$0;},set_shader:function(value){this.$0=value;return value;}}
Type.registerNamespace('GLSharp.Universe');GLSharp.Universe.Component=function(){}
GLSharp.Universe.Component.prototype={$0:null,get_type:function(){return this.$0;},set_type:function(value){this.$0=value;return value;},$1:null,get_parent:function(){return this.$1;},set_parent:function(value){this.$1=value;return value;}}
GLSharp.Universe.Node=function(){this.$3={};}
GLSharp.Universe.Node.prototype={add_componentAdded:function(value){this.$0=ss.Delegate.combine(this.$0,value);},remove_componentAdded:function(value){this.$0=ss.Delegate.remove(this.$0,value);},$0:null,add_componentRemoved:function(value){this.$1=ss.Delegate.combine(this.$1,value);},remove_componentRemoved:function(value){this.$1=ss.Delegate.remove(this.$1,value);},$1:null,$2:'Undefined',get_name:function(){return this.$2;},set_name:function(value){this.$2=value;return value;},addComponent:function(component){this.$3[component.get_type()]=component;if(this.$0!=null){this.$0(this,component);}},removeComponent:function(component){delete this.$3[component.get_type()];if(this.$1!=null){this.$1(this,component);}}}
GLSharp.Universe.World=function(){this.$0=[];}
GLSharp.Universe.World.prototype={$0:null,get_rootNodes:function(){return this.$0;},add_nodeAdded:function(value){this.$1=ss.Delegate.combine(this.$1,value);},remove_nodeAdded:function(value){this.$1=ss.Delegate.remove(this.$1,value);},$1:null,add_nodeRemoved:function(value){this.$2=ss.Delegate.combine(this.$2,value);},remove_nodeRemoved:function(value){this.$2=ss.Delegate.remove(this.$2,value);},$2:null,addNode:function(node){this.$0.add(node);if(this.$1!=null){this.$1(this,node);}},removeNode:function(node){this.$0.remove(node);if(this.$2!=null){this.$2(this,node);}}}
GLSharp.Graphics.Color.registerClass('GLSharp.Graphics.Color');GLSharp.Graphics.Material.registerClass('GLSharp.Graphics.Material');GLSharp.Universe.Component.registerClass('GLSharp.Universe.Component');GLSharp.Universe.Node.registerClass('GLSharp.Universe.Node');GLSharp.Universe.World.registerClass('GLSharp.Universe.World');})();// This script was generated using Script# v0.7.4.0
